name: i_baza_catalog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  hive: any
  hive_flutter: any
  cupertino_icons: ^1.0.2
  path_provider: any
  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  pintextfield: ^0.1.1
  pin_code_fields: any
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  open_file: any
  share_plus: any
  flutter_svg: ^0.22.0
  get_it: ^7.6.7
  gap: ^3.0.1
  pinput: ^3.0.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  hive_generator: any
  objectbox_generator: any

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/svg/
    - assets/profile_icons/
    - assets/icon/login/
    - assets/icon/profile/
    - assets/icon/catalog/
    - assets/icon/appBar/
    - assets/images/
    - assets/images/category/
    - assets/icon/bottom_bar/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
