List<String> containerName = [
  "Kiyim va poyabzallar",
  "Uy uchun",
  "Bolalar uchun",
  "Oziq-ovqat mahsulotlari",
  "Go'zalik va gigiyena",
  "Dorixona",
  """"Zoo" mahsulotlar""",
  "Maishiy kimyo mahsulotlari",
  "Sport mahsulotlari",
  "Avtomobillar uchun",
  "Elektronika",
  "Kompyuterlar",
  "Maishiy texnika",
  "Mebel",
  "Qurilish va ta'mirlash",
  "Maktab va ofis uchun",
  "Gullar",
  "Zargarlik buyumlari",
  "Uy va bog'",
  "Uskunalar",
];