List<String> imageUrls = [
  "assets/catalog/koylak.png",
  // "assets/catalog/koylak2.png",
  // "assets/catalog/koylak3.png",
  "assets/catalog/yostiq.png",
  "assets/catalog/quyoncha.png",
  "assets/catalog/karam.png",
  "assets/catalog/atir.png",
  "assets/catalog/dori.png",
  "assets/catalog/kosa.png",
  "assets/catalog/suv_sepgich.png",
  "assets/catalog/basketball.png",
  "assets/catalog/balon.png",
  "assets/catalog/pult.png",
  "assets/catalog/noutbook.png",
  "assets/catalog/kir_mashina.png",
  "assets/catalog/divan.png",
  "assets/catalog/drell.png",
  "assets/catalog/daftar.png",
  "assets/catalog/gullar.png",
  "assets/catalog/uzuk.png",
  "assets/catalog/gulga_suv_quygich.png",
  // "assets/catalog/terminal.png",
  "assets/catalog/terminal2.png",
  // "assets/catalog/terminal3.png",

];